### ISSUE TITLE
"undefined reference to symbol 'g_error_free'" when building with pango 1.43.0

### ISSUE THREAD

**Issue by Ferdi265** [emersion/mako#104]
Since updating to pango version 1.43.0 from 1.42.4, mako doesn't build. Instead it errors out with this message:

```
/usr/bin/ld: mako@exe/render.c.o: undefined reference to symbol 'g_error_free'
/usr/bin/ld: /usr/lib/libglib-2.0.so.0: error adding symbols: DSO missing from command line
```

Full build log is [here](https://gist.github.com/Ferdi265/ede103e0768ce0a3733570f751a88e7a)

Downgrading to an older version of pango (tested 1.42.4) fixes the issue

**Comment by Emantor** [comment]
There is already a fix in the pango repo: https://github.com/GNOME/pango/commit/d0cb6be7431d1a3c711bd45bcf05b34601604037
Unfortunately it is not contained in a release yet.

**Comment by emersion** [comment]
The Arch package has been fixed in https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pango&id=2e34c899b1bec29643ea4b94c6714b0966fa84fb
